### ISSUE TITLE
[error]请确保urls.txt（目标网站/页面的链接）和rules.txt（规则文件）位于本目录下

### ISSUE THREAD

**Issue by little-2pig** [heikanet/Hawkeye#1]
已在当前目录为何还会识别不到

**Comment by spaceman-911** [comment]
> 

24行、27行加一下，encoding='utf-8' 这个编码规则，然后可能还需要命令行执行：playwright install --force chromium 和 playwright install --force chrome，如果也不行可以打印报错看看

**Comment by ghost** [comment]
发一个加好的能直接用的版本能行吗？

**Comment by ssrsec** [comment]
编码问题已解决。依赖问题请看readme
