### ISSUE TITLE
监测目标一直无法访问

### ISSUE THREAD

**Issue by little-2pig** [heikanet/Hawkeye#2]
![image](https://user-images.githubusercontent.com/58223422/196036399-789c5ff1-4eac-40d9-a0d5-c33e3627d68a.png)
确认过目标访问无异常，URL格式 http://XXXX/ 或者 http://xxxx 都不行

**Comment by ssrsec** [comment]
> 

# 下载和安装依赖的浏览器
playwright install --force chromium
playwright install --force chrome
